[package]
name = "paillier-zk"
version = "0.4.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "ZK-proofs for Paillier encryption scheme"
repository = "https://github.com/LFDT-Lockness/paillier-zk"
categories = ["algorithms", "cryptography"]
keywords = ["paillier", "zk-proofs", "zero-knowledge"]

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec = {git="https://github.com/nxhieu3102/generic-ec", branch="feat/integrate-cggmp21" , features = ["udigest"] }
fast-paillier = { path = "../fork-fast-paillier" }
rand_core = { version = "0.6", default-features = false }
digest = "0.10"
rand_hash = "0.1"
thiserror = "1"
serde = { version = "1", features = ["derive"], optional = true }
serde_with = { version = "3", default-features = false, features = [
    "macros",
], optional = true }
udigest = { version = "0.2.1", default-features = false, features = [
    "inline-struct",
    "derive",
    "alloc",
] }
malachite = { path = "../fork-malachite/malachite" }
malachite-base = { path = "../fork-malachite/malachite-base" }
malachite-bigint = { path = "../fork-malachite/malachite-bigint" }
malachite-nz = { path = "../fork-malachite/malachite-nz" }

# WASM dependencies
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", features = ["console"], optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }

[dev-dependencies]
generic-ec = { git="https://github.com/nxhieu3102/generic-ec", branch="feat/integrate-cggmp21", features = ["udigest", "all-curves"] }
rand_dev = { version = "0.1", default-features = false }
sha2 = { version = "0.10", default-features = false }

subtle = { version = "2.4", default-features = false }
zeroize = { version = "1.5", default-features = false }

anyhow = "1"
serde_json = "1"

# WASM test dependencies
wasm-bindgen-test = "0.3"

[features]
default = []
serde = [
    "dep:serde",
    "dep:serde_with",
    "generic-ec/serde",
    "fast-paillier/serde",
]
wasm = [
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures", 
    "dep:js-sys",
    "dep:web-sys",
    "dep:console_error_panic_hook",
    "dep:wee_alloc",
    "dep:getrandom",
    "serde"
]

# This features is exlusively used for `cargo test --doc`
__internal_doctest = ["serde"]

[[example]]
name = "pregenerate"
required-features = ["serde"]

[package.metadata.docs.rs]
all-features = true
